"""Packs rendered frames into a PixiJS-readable sprite atlas.

Deliberately the simplest thing that works: a fixed-size grid, since every
walker frame shares one canvas size (see walkers.py). A real bin-packer
would save a handful of pixels on a texture that is already a few kilobytes
— not worth the code it would take to review.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

from PIL import Image


def pack(frames: dict[str, Image.Image], image_name: str, columns: int = 16) -> tuple[Image.Image, dict]:
    """Lays the frames out row-major and returns the sheet plus its PixiJS
    `Spritesheet` descriptor. Keys are emitted sorted so the output is
    deterministic — the atlas is committed, and a sheet that reshuffled
    itself on every run would produce a meaningless diff each time."""
    if not frames:
        raise ValueError("no frames to pack")

    keys = sorted(frames)
    widths = {image.width for image in frames.values()}
    heights = {image.height for image in frames.values()}
    if len(widths) != 1 or len(heights) != 1:
        raise ValueError("pack() assumes uniform frame sizes; got widths=%s heights=%s" % (widths, heights))
    frame_width, frame_height = widths.pop(), heights.pop()

    rows = math.ceil(len(keys) / columns)
    sheet = Image.new("RGBA", (columns * frame_width, rows * frame_height), (0, 0, 0, 0))

    descriptor: dict[str, dict] = {}
    for index, key in enumerate(keys):
        x = (index % columns) * frame_width
        y = (index // columns) * frame_height
        sheet.paste(frames[key], (x, y))
        descriptor[key] = {
            "frame": {"x": x, "y": y, "w": frame_width, "h": frame_height},
            "sourceSize": {"w": frame_width, "h": frame_height},
            "spriteSourceSize": {"x": 0, "y": 0, "w": frame_width, "h": frame_height},
            "rotated": False,
            "trimmed": False,
        }

    meta = {
        "frames": descriptor,
        "meta": {
            "image": image_name,
            "format": "RGBA8888",
            "size": {"w": sheet.width, "h": sheet.height},
            "scale": "1",
            "comment": "Generated by tools/generate_sprites.py — do not edit. Run `npm run sprites`.",
        },
    }
    return sheet, meta


def write(sheet: Image.Image, meta_json: str, png_path: Path, json_path: Path) -> None:
    png_path.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(png_path, format="PNG", optimize=True)
    json_path.write_text(meta_json, encoding="utf-8")
