import type { FactionId, HouseLevel } from "../game/components";
import atlasData from "../assets/sprites/houses.json";
import atlasUrl from "../assets/sprites/houses.png";
import { SpriteAtlas } from "./spriteSheet";

/**
 * The building sprite atlas — generated by tools/generate_sprites.py from
 * tools/sprites/houses.py, replacing the procedural isometric geometry that
 * used to live in pixelArt.ts (drawWalls / drawHipRoof / drawCastle).
 *
 * That code could only emit flat-shaded polygons. It had no way to put a
 * thatch course, a stone joint, a lit window or a silhouette outline on a
 * wall, because each of those is a per-pixel decision and it worked in
 * floating-point polygon space.
 *
 * Only 8 frames — 4 levels x 2 factions. Buildings don't animate, and the
 * faction only reaches the flag (per plan/archived/0085 the original never
 * tinted a whole structure a team color), so there is no larger matrix.
 */
export function houseFrameKey(faction: FactionId, level: HouseLevel): string {
  return `house_${faction}_${level}`;
}

/** Every frame key present in the committed atlas. Exported for the test. */
export const ATLAS_FRAME_KEYS: readonly string[] = Object.keys(atlasData.frames);

const atlas = new SpriteAtlas(atlasUrl, atlasData);

export const loadHouseSprites = (): Promise<void> => atlas.load();
export const houseTexture = (key: string) => atlas.texture(key);
