import type { FactionId, HeroKind, WalkerState } from "../game/components";
import atlasData from "../assets/sprites/walkers.json";
import atlasUrl from "../assets/sprites/walkers.png";
import { SpriteAtlas } from "./spriteSheet";

/**
 * The 4 isometric movement directions a walker's own tile-space heading
 * quantizes to — see facingFor() in EntityLayer.ts. These match the 4
 * screen-space diagonals a 2:1 iso projection produces from the 4 tile-axis
 * directions (+-x, +-y), which is why they carry the terrain/camera's own
 * compass names rather than "up/down/left/right".
 *
 * "S*" faces toward the camera (front and eyes visible), "N*" away; "*W" is
 * the horizontal mirror of its "*E" counterpart. tools/sprites/walkers.py
 * reads the name the same way when it draws the frames.
 */
export type Facing = "NE" | "NW" | "SE" | "SW";

/**
 * The walker sprite atlas — generated by tools/generate_sprites.py from the
 * drawing code in tools/sprites/walkers.py.
 *
 * The whole appearance matrix is baked in (192 frames: 2 factions x 6 poses
 * x 4 facings x 4 walk-cycle frames), so nothing here tints or composites
 * at runtime — a frame key picks a finished picture. Runtime tinting would
 * not work anyway: Pixi's tint multiplies the entire sprite, dragging the
 * skin and boot colors along with the clothing.
 */

/**
 * A walker's appearance variant. Leader and hero are independent — a leader
 * can be promoted, and both marks are drawn in that case — so the pairs are
 * enumerated rather than treated as mutually exclusive.
 */
export type WalkerPose =
  | "plain"
  | "leader"
  | "perseus"
  | "hercules"
  | "odysseus"
  | "achilles"
  | "adonis"
  | "helen"
  | "guardian"
  | "leaderPerseus"
  | "leaderHercules"
  | "leaderOdysseus"
  | "leaderAchilles"
  | "leaderAdonis"
  | "leaderHelen"
  | "leaderGuardian";

export type { HeroKind };

/**
 * What the walker is doing, on top of which way it faces — see ACTIONS in
 * tools/sprites/walkers.py.
 *
 * "seeking" and "traveling" deliberately share the walking art: both are a
 * person going somewhere, and inventing a visible difference the player
 * cannot act on would be noise. Fighting and drowning are the two states
 * that change what the player should do.
 */
export type WalkerAction = "walk" | "fight" | "drown";

/**
 * Frames in one walk cycle: contact, passing, contact, passing. Two frames
 * (what this started with) read as a twitch at this size; four read as
 * walking, because the passing poses lift the figure a pixel while the
 * contact poses plant it and the two contacts swing opposite arms.
 */
export const WALK_FRAMES = 4;

export function walkerPose(isLeader: boolean, heroKind?: HeroKind): WalkerPose {
  if (!heroKind) return isLeader ? "leader" : "plain";
  if (!isLeader) return heroKind;
  // "leader" + the hero's own name, capitalized — the same rule
  // tools/sprites/walkers.py's POSES uses to name the paired frames, so
  // adding a hero never means editing a lookup table on either side.
  return `leader${heroKind[0].toUpperCase()}${heroKind.slice(1)}` as WalkerPose;
}

/**
 * Must agree exactly with frame_key() in tools/sprites/walkers.py — the two
 * sides independently build the same string, and a mismatch would surface
 * only as an invisible walker at runtime. walkerSprites.test.ts checks
 * every key this can produce against the committed atlas.
 */
export function walkerFrameKey(
  faction: FactionId,
  pose: WalkerPose,
  action: WalkerAction,
  facing: Facing,
  frame: number,
): string {
  return `walker_${faction}_${pose}_${action}_${facing}_${frame}`;
}

/**
 * The action a walker is currently in, from the state EntityLayer already
 * has. Drowning wins over fighting: a walker going under has stopped being
 * a combatant, and that is the more urgent thing for the player to see.
 */
export function walkerAction(state: WalkerState, isDrowning: boolean): WalkerAction {
  if (isDrowning) return "drown";
  return state === "fighting" ? "fight" : "walk";
}

/** Every frame key present in the committed atlas. Exported for the test. */
export const ATLAS_FRAME_KEYS: readonly string[] = Object.keys(atlasData.frames);

const atlas = new SpriteAtlas(atlasUrl, atlasData);

export const loadWalkerSprites = (): Promise<void> => atlas.load();
export const walkerTexture = (key: string) => atlas.texture(key);
