import type { FactionId } from "../game/components";
import atlasData from "../assets/sprites/walkers.json";
import atlasUrl from "../assets/sprites/walkers.png";
import { SpriteAtlas } from "./spriteSheet";

/**
 * The 4 isometric movement directions a walker's own tile-space heading
 * quantizes to — see facingFor() in EntityLayer.ts. These match the 4
 * screen-space diagonals a 2:1 iso projection produces from the 4 tile-axis
 * directions (+-x, +-y), which is why they carry the terrain/camera's own
 * compass names rather than "up/down/left/right".
 *
 * "S*" faces toward the camera (front and eyes visible), "N*" away; "*W" is
 * the horizontal mirror of its "*E" counterpart. tools/sprites/walkers.py
 * reads the name the same way when it draws the frames.
 */
export type Facing = "NE" | "NW" | "SE" | "SW";

/**
 * The walker sprite atlas — generated by tools/generate_sprites.py from the
 * drawing code in tools/sprites/walkers.py.
 *
 * The whole appearance matrix is baked in (192 frames: 2 factions x 6 poses
 * x 4 facings x 4 walk-cycle frames), so nothing here tints or composites
 * at runtime — a frame key picks a finished picture. Runtime tinting would
 * not work anyway: Pixi's tint multiplies the entire sprite, dragging the
 * skin and boot colors along with the clothing.
 */

/**
 * A walker's appearance variant. Leader and hero are independent — a leader
 * can be promoted, and both marks are drawn in that case — so the pairs are
 * enumerated rather than treated as mutually exclusive.
 */
export type WalkerPose = "plain" | "leader" | "knight" | "guardian" | "leaderKnight" | "leaderGuardian";

export type HeroKind = "knight" | "guardian";

/**
 * Frames in one walk cycle: contact, passing, contact, passing. Two frames
 * (what this started with) read as a twitch at this size; four read as
 * walking, because the passing poses lift the figure a pixel while the
 * contact poses plant it and the two contacts swing opposite arms.
 */
export const WALK_FRAMES = 4;

export function walkerPose(isLeader: boolean, heroKind?: HeroKind): WalkerPose {
  if (!heroKind) return isLeader ? "leader" : "plain";
  if (!isLeader) return heroKind;
  return heroKind === "knight" ? "leaderKnight" : "leaderGuardian";
}

/**
 * Must agree exactly with frame_key() in tools/sprites/walkers.py — the two
 * sides independently build the same string, and a mismatch would surface
 * only as an invisible walker at runtime. walkerSprites.test.ts checks
 * every key this can produce against the committed atlas.
 */
export function walkerFrameKey(faction: FactionId, pose: WalkerPose, facing: Facing, frame: number): string {
  return `walker_${faction}_${pose}_${facing}_${frame}`;
}

/** Every frame key present in the committed atlas. Exported for the test. */
export const ATLAS_FRAME_KEYS: readonly string[] = Object.keys(atlasData.frames);

const atlas = new SpriteAtlas(atlasUrl, atlasData);

export const loadWalkerSprites = (): Promise<void> => atlas.load();
export const walkerTexture = (key: string) => atlas.texture(key);
