import { Assets, Spritesheet, Texture, type SpritesheetData } from "pixi.js";
import type { FactionId } from "../game/components";
import atlasData from "../assets/sprites/walkers.json";
import atlasUrl from "../assets/sprites/walkers.png";
import type { Facing } from "./pixelArt";

/**
 * The walker sprite atlas — generated by tools/generate_sprites.py from the
 * drawing code in tools/sprites/walkers.py, per the tooling direction agreed
 * in plan/0089. Walkers used to be emitted as a few dozen `Graphics.rect`
 * calls per walker per frame; they are now one textured quad each, drawn from
 * a 488-byte atlas.
 *
 * The whole appearance matrix is baked into the atlas (96 frames: 2 factions
 * x 6 poses x 4 facings x 2 walk-cycle frames), so nothing here tints or
 * composites at runtime — a frame key picks a finished picture. Runtime
 * tinting would not work anyway: Pixi's tint multiplies the entire sprite,
 * which would drag the skin and boot colors along with the clothing.
 */

/**
 * A walker's appearance variant. Leader and hero are independent — a leader
 * can be promoted, and both marks are drawn in that case — so the pairs are
 * enumerated rather than treated as mutually exclusive.
 */
export type WalkerPose = "plain" | "leader" | "knight" | "guardian" | "leaderKnight" | "leaderGuardian";

export type HeroKind = "knight" | "guardian";

export function walkerPose(isLeader: boolean, heroKind?: HeroKind): WalkerPose {
  if (!heroKind) return isLeader ? "leader" : "plain";
  if (!isLeader) return heroKind;
  return heroKind === "knight" ? "leaderKnight" : "leaderGuardian";
}

/**
 * Must agree exactly with frame_key() in tools/sprites/walkers.py — the two
 * sides independently build the same string, and a mismatch would surface
 * only as an invisible walker at runtime. walkerSprites.test.ts checks every
 * key this can produce against the committed atlas, which is what actually
 * keeps the two in step.
 */
export function walkerFrameKey(faction: FactionId, pose: WalkerPose, facing: Facing, stepping: boolean): string {
  return `walker_${faction}_${pose}_${facing}_${stepping ? "step" : "stand"}`;
}

/** Every frame key present in the committed atlas. Exported for the test. */
export const ATLAS_FRAME_KEYS: readonly string[] = Object.keys(atlasData.frames);

let sheet: Spritesheet | undefined;

/**
 * Parses the atlas. Call once during startup and await it before the first
 * frame — main.ts does — so that update() can look frames up synchronously.
 */
export async function loadWalkerSprites(): Promise<void> {
  if (sheet) return;
  const texture = await Assets.load<Texture>(atlasUrl);
  // Nearest, not linear: the atlas is authored at roughly one art pixel per
  // screen pixel and scaled up for leaders, and bilinear filtering would
  // smear a 5x9 sprite into mush.
  texture.source.scaleMode = "nearest";
  const parsed = new Spritesheet(texture, atlasData as unknown as SpritesheetData);
  await parsed.parse();
  sheet = parsed;
}

/**
 * The texture for one frame key, or undefined before loadWalkerSprites()
 * has resolved. Callers skip drawing rather than throwing: a walker missing
 * for the frame or two before the atlas parses is far better than a crash,
 * and the test above is what catches a genuinely wrong key.
 */
export function walkerTexture(key: string): Texture | undefined {
  return sheet?.textures[key];
}
